- hosts: lxd
  become_user: root
  vars:
    ansible_ssh_user: root
    ansible_ssh_private_key_file: "../../terraform/root_ssh.key"
  tasks:
    - name: "apt update"
      apt:
         update_cache: yes
    - name: "install build-essential"
      apt:
        pkg: build-essential
    - name: "install lxd"
      apt:
        pkg: lxd
    - name: "lxd user group"
      user:
        name: devops
        groups: lxd
    - name: "lxd init"
      become_user: devops
      shell: lxc config set core.https_address :8443
