---
- hosts: web lxd
  become_user: root
  gather_facts: no # no python yet
  pre_tasks:
    - name: 'install python2'
      raw: apt-get -y install python-simplejson
    - action: setup

  vars:
    ansible_ssh_user: root
    ansible_ssh_private_key_file: "../../terraform/root_ssh.key"
  tasks:
    - name: "hostname {{inventory_hostname}}"
      hostname:
        name: "{{inventory_hostname}}"

    - name: "/etc/hosts"
      copy:
        src: ../../terraform/hosts.key
        dest: /etc/hosts

    - name: "create devops unix user"
      user:
        name: devops
        generate_ssh_key: yes
        ssh_key_type: ed25519
