- hosts: lxd
  become_user: root
  vars:
    ansible_ssh_user: root
    ansible_ssh_private_key_file: "../../terraform/root_ssh.key"
  tasks:
    - name: "apt update"
      apt:
         update_cache: yes
    - name: "install build-essential"
      apt:
        pkg: build-essential
    - name: "install lxd"
      apt:
        pkg: lxd
