- hosts: lxd
  become_user: root
  vars:
    ansible_ssh_user: root
    ansible_ssh_private_key_file: "../../terraform/root_ssh.key"
  tasks:
    - name: "apt update"
      apt:
         update_cache: yes
    - name: "install build-essential"
      apt:
        pkg: build-essential
    - name: "install lxd"
      apt:
        pkg: lxd
    - name: "lxd user group"
      user:
        name: devops
        groups: lxd
    - name: "lxd config https"
      become_user: devops
      shell: lxc config set core.https_address :8443
# todo: selfsigned key gen; scp; lxc config trust add /tmp/client.crt
    - name: 'git clone lxd-container'
      git:
        repo: 'https://github.com/cointhink/lxd-container'
        dest: /home/devops/lxd-container
    - name: 'git clone scripting'
      git:
        repo: 'https://github.com/cointhink/scripting'
        dest: /home/devops/scripting
    - name: 'git clone protobuf'
      git:
        repo: 'https://github.com/cointhink/protobuf'
        dest: /home/devops/protobuf
