#cloud-config
hostname: vultr-db-2

ssh_authorized_keys:
  - ${ssh_key}


coreos:
  update:
    reboot-strategy: off
  units:
    - name: 20-eth1-static.network
      content: |
        [Match]
        Name=eth1

        [Network]
        Address=10.0.0.4/24

    - name: mnt-ocean.mount
      command: start
      content: |
        [Mount]
        What=/dev/vdb1
        Where=/mnt/ocean
        Type=ext4
        [Install]
        WantedBy=multi-user.target

    - name: sshd.service
      enable: true

    - name: sshd.socket
      mask: true

    - name: postgres-docker.service
      command: start
      content: |
        [Unit]
        Description=Starts postgres
        After=docker.service
        Requires=docker.service
        [Service]
        Restart=always
        ExecStart=/usr/bin/docker run --rm -p 5432:5432 -v /mnt/ocean/postgres:/postgres -e PGDATA=/postgres postgres:alpine
        [Install]
        WantedBy=local.target

