#!/bin/bash

TO=`/usr/local/bin/hjson -j /home/devops/api-go/config.hjson  | jq -r .email.admin`
/usr/bin/sendmail -t <<ERRMAIL
To: $1
From: systemd <root@$HOSTNAME>
Subject: $2
Content-Transfer-Encoding: 8bit
Content-Type: text/plain; charset=UTF-8

$(systemctl status --full "$2")
ERRMAIL
